services:
  postgres:
    image: postgres:16
    container_name: nextfarm-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CLRinmymind5
      POSTGRES_DB: nextfarm_voicelog

    ports:
      - "1275:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile

    container_name: nextfarm-ai-service

    ports:
      - "8000:8000"

    env_file:
      - ./ai-service/.env

    volumes:
      - ./ai-service/uploads:/app/uploads
      - ./ai-service/.whisper-cache:/root/.cache/whisper

    restart: unless-stopped

volumes:
  postgres_data: